version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 5

  web:
    build: .
    image: sadidocker/farm_app
    entrypoint: [ "./wait-for-it.sh", "${DB_HOST}:5432", "--timeout=60", "--strict", "--" ]
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn farm_app.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./staticfiles:/tmp/app-resources/staticfiles
      - media_data:/app/media/uploads
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./static:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx/conf.d/web.conf:/etc/nginx/conf.d/web.conf:ro
    depends_on:
      - web

volumes:
  postgres_data:
  media_data: