# Generated by Django 4.2.11 on 2024-12-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_animalproduct_photo_alter_dairyproduct_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dairyproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nut',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vegetableandfruit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
