# Generated by Django 4.2.11 on 2024-12-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_farmeruser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmeruser',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
