# Generated by Django 4.2.11 on 2024-12-01 13:01

from django.db import migrations, models
import farm_app.catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_farmeruser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmeruser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[farm_app.catalog.validators.validate_image_size]),
        ),
    ]
