# Generated by Django 4.2.11 on 2024-12-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
    ]
